name: Streamlit Weaviate Chat
language: python
variables:
  - name: weaviate_rest_endpoint
    inputType: FreeText
    description: ''
    defaultValue: https://quix-demo-adk86m6q.weaviate.network
    required: false
  - name: weaviate_api_key
    inputType: Secret
    description: ''
    defaultValue: weaviate_apikey
    required: false
  - name: collectionname
    inputType: FreeText
    description: ''
    defaultValue: Transcript
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
